platform :ios, "8.0"
pod 'OpenUDID'
pod "Aspects"
pod "IQKeyboardManager"
pod 'ReactiveCocoa'
pod "MWPhotoBrowser"
pod 'FMDB', :git => 'https://github.com/ccgus/fmdb.git'
pod 'AliyunOSSiOS'
use_frameworks!
pod "SDWebImage"
pod 'Alamofire'
pod 'Result', :git => 'https://github.com/antitypical/Result.git'
pod 'Box'
